# ╔══════════════════════════════════════════════════════════╗
# ║           OMGENTLY — Hypridle (Idle Daemon)             ║
# ╚══════════════════════════════════════════════════════════╝

general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# ── 5 menit: Lock screen ─────────────────────────────────
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# ── 8 menit: Matikan layar ───────────────────────────────
listener {
    timeout = 480
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
