name: Ansible Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install ansible-core and ansible-lint
        run: pip install ansible-core ansible-lint

      - name: Run ansible-lint
        run: ansible-lint site.yml

      - name: Syntax Check
        run: ansible-playbook -i 'localhost,' -c local --syntax-check site.yml
